development:
  adapter: postgresql
  database: convention_development

test:
  adapter: postgresql
  database: convention_test

production:
  adapter: postgresql
  encoding: unicode
  database: project_production